server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://34.135.106.200:3306/telemedapp
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true